// Code generated by ogen, DO NOT EDIT.

package openapi

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// GetLogin implements getLogin operation.
//
// List accounts and the current authorization request.
//
// GET /api/v1/login
func (UnimplementedHandler) GetLogin(ctx context.Context, params GetLoginParams) (r GetLoginRes, _ error) {
	return r, ht.ErrNotImplemented
}
