// Code generated by ogen, DO NOT EDIT.

package openapi

import (
	"net/http"

	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
	"github.com/ogen-go/ogen/validate"
)

// GetLoginParams is parameters of getLogin operation.
type GetLoginParams struct {
	FakeOidcBrowser OptString `json:",omitempty,omitzero"`
	Request         OptString `json:",omitempty,omitzero"`
}

func unpackGetLoginParams(packed middleware.Parameters) (params GetLoginParams) {
	{
		key := middleware.ParameterKey{
			Name: "fake_oidc_browser",
			In:   "cookie",
		}
		if v, ok := packed[key]; ok {
			params.FakeOidcBrowser = v.(OptString)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "request",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Request = v.(OptString)
		}
	}
	return params
}

func decodeGetLoginParams(args [0]string, argsEscaped bool, r *http.Request) (params GetLoginParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	c := uri.NewCookieDecoder(r)
	// Decode cookie: fake_oidc_browser.
	if err := func() error {
		cfg := uri.CookieParameterDecodingConfig{
			Name:    "fake_oidc_browser",
			Explode: true,
		}
		if err := c.HasParam(cfg); err == nil {
			if err := c.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotFakeOidcBrowserVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotFakeOidcBrowserVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.FakeOidcBrowser.SetTo(paramsDotFakeOidcBrowserVal)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if value, ok := params.FakeOidcBrowser.Get(); ok {
					if err := func() error {
						if err := (validate.String{
							MinLength:     0,
							MinLengthSet:  false,
							MaxLength:     128,
							MaxLengthSet:  true,
							Email:         false,
							Hostname:      false,
							Regex:         nil,
							MinNumeric:    0,
							MinNumericSet: false,
							MaxNumeric:    0,
							MaxNumericSet: false,
						}).Validate(string(value)); err != nil {
							return errors.Wrap(err, "string")
						}
						return nil
					}(); err != nil {
						return err
					}
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "fake_oidc_browser",
			In:   "cookie",
			Err:  err,
		}
	}
	// Decode query: request.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "request",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotRequestVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotRequestVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Request.SetTo(paramsDotRequestVal)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if value, ok := params.Request.Get(); ok {
					if err := func() error {
						if err := (validate.String{
							MinLength:     0,
							MinLengthSet:  false,
							MaxLength:     128,
							MaxLengthSet:  true,
							Email:         false,
							Hostname:      false,
							Regex:         nil,
							MinNumeric:    0,
							MinNumericSet: false,
							MaxNumeric:    0,
							MaxNumericSet: false,
						}).Validate(string(value)); err != nil {
							return errors.Wrap(err, "string")
						}
						return nil
					}(); err != nil {
						return err
					}
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "request",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}
