// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type Error = {
    code: ErrorCode;
};

export type ErrorCode = 'accounts_unavailable' | 'invalid_request';

export type Login = {
    can_login: boolean;
    client_name: string;
    redirect_host: string;
    users: Array<User>;
};

export type User = {
    email: string;
    /**
     * Optional account identifier displayed instead of email.
     */
    identifier?: string;
    name: string;
    subject: string;
};

export type GetLoginData = {
    body?: never;
    path?: never;
    query?: {
        request?: string;
    };
    url: '/api/v1/login';
};

export type GetLoginErrors = {
    /**
     * Authorization request is expired or belongs to another browser.
     */
    400: Error;
    /**
     * The configured user source is unavailable.
     */
    503: Error;
};

export type GetLoginError = GetLoginErrors[keyof GetLoginErrors];

export type GetLoginResponses = {
    /**
     * Accounts and authorization context.
     */
    200: Login;
};

export type GetLoginResponse = GetLoginResponses[keyof GetLoginResponses];
